[package]
name = "request-test"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
tower = "0.4.13"
serde ={ version = "*", features = ["derive"]}
serde_json = "1.0.117"
axum-extra = { version = "0.9.3", features = ["cookie"] }
